name: sstcam-common CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: sstcam/sstcam-build
        token: ${{ secrets.SSTCAM_PAT }}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
          pip install pyyaml numpy
          pip install .
    - name: setup build
      run: |
          mkdir project
          cd project
          sc-build init
          cd build
    - name: configure build
      run: |
        cmake .. 
          
    - name: make
      run: make
    - name: test
      run: ctest
