name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: sstcam/sstcam-build
        token: ${{ secrets.SSTCAM_PAT }}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
          pip install pyyaml numpy
          pip install .
          mkdir FitsIO
          cd FitsIO
          wget http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio-3.47.tar.gz 
          tar -xvf cfitsio-3.47.tar.gz
          cd cfitsio-3.47
          ./configure --prefix=/usr/local
          sudo make
          sudo make install
    - name: setup build
      run: |
          mkdir project
          cd project
          sc-build init
          cd build
    - name: configure build
      run: |
        cd project/build
        cmake .. 
          
    - name: make
      run:  |
        cd project/build
        make
    - name: test
      run:   |
        cd project/build
        ctest

